filenames:
  - /var/log/syslog
labels:
  type: syslog
---
source: journalctl
journalctl_filter:
  - "--directory=/var/log/host/"
labels:
  type: syslog
---
poll_without_inotify: false
filenames:
  - /var/log/traefik/*.log
labels:
  type: traefik
---
listen_addr: 0.0.0.0:7422
appsec_config: crowdsecurity/appsec-default
name: myAppSecComponent
source: appsec
labels:
  type: appsec
