on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  apply:
    runs-on: ubuntu-latest
    env:
      HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
      CLOUDFLARE_R2_ENDPOINT: ${{ vars.CLOUDFLARE_R2_ENDPOINT }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - run: |
          go install github.com/google/yamlfmt/cmd/yamlfmt@latest
          go install mvdan.cc/sh/v3/cmd/shfmt@latest
      - uses: opentofu/setup-opentofu@v1
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.CLOUDFLARE_R2_KEY }}
          aws-secret-access-key: ${{ secrets.CLOUDFLARE_R2_SECRET }}
          aws-region: auto
        continue-on-error: true
      - run: ./bin/get-tfstate.sh
        continue-on-error: true
      - run: tofu fmt -check
      - run: shfmt -d bin/*.sh
      - run: yamlfmt -lint coreos/*.bu .github/actions/*.yml
      - run: tofu init
      - run: tofu validate -no-color
      - run: tofu plan -out=out.tfplan
      - run: tofu apply -auto-approve out.tfplan
      - run: ./bin/put-tfstate.sh
