on:
  push:
    branches:
      - main

jobs:
  tofu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
      - run: tofu fmt -check
      - run: tofu init
      - run: tofu validate -no-color
      - run: tofu plan
      - run: tofu apply
