on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.CLOUDFLARE_R2_KEY }}
          aws-secret-access-key: ${{ secrets.CLOUDFLARE_R2_SECRET }}
          aws-region: auto
        continue-on-error: true
      - run: |
          wget -q -O /usr/local/bin/butane \
            https://github.com/coreos/butane/releases/download/v0.23.0/butane-x86_64-unknown-linux-gnu
          wget -q https://github.com/coreos/butane/releases/download/v0.23.0/butane-x86_64-unknown-linux-gnu.asc
          curl -s https://fedoraproject.org/fedora.gpg | gpg --import
          gpg --verify butane-x86_64-unknown-linux-gnu.asc /usr/local/bin/butane
          chmod +x /usr/local/bin/butane
      - run: |
          aws s3api get-object --bucket infra --key terraform.tfstate \
            --endpoint-url ${{ vars.CLOUDFLARE_R2_ENDPOINT }} \
            terraform.tfstate
        continue-on-error: true
      - run: tofu init
      - run: tofu validate -no-color
      - run: tofu destroy -auto-approve -exclude=hcloud_volume.internal_net_vol
      - run: |
          aws s3api put-object --bucket infra --key terraform.tfstate --body terraform.tfstate \
            --endpoint-url ${{ vars.CLOUDFLARE_R2_ENDPOINT }} \
            --checksum-algorithm CRC32
